appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: s94ZETYJ54+GpkrEgpvqNGSagpyUOWwfW+vQteXkvXCbvTmibonTw/bZgBTv2wvvjX4NZ8gfuzIIDZwbCouQcK1dIlU8R+gIybfcrIW0pAnWrk2k+hI3jRXjUWothSvEA3rZgGyWYXP9EHXYKGlrUYJvwJ67DDzw0XOjohL4DMQd1MRRcz1suH/v0JPCCS+uKiobNoT3+SbMlfPtdAzZZ/XhDAOvoIexwvV3aklXM7Me/qPgLDgjAMUgYhu+mA9Vo3gVIHidHTboGPr5wEU3DFLPf4AuvrUHICIJpwvTZgjhIGyvLyWI3ySMteyf0TtDKwSEJbQY0zVJ1miwxobIoeWiwj97/j2Yzv/DSKWzJYJca4DmGEi5aWAJf432GCmMmrsjvVlrAfORsz/AjC2UyiN+/owNaLz/z3PiuzMX5WmGwhBhiqP0JlQCayKOzRRN07HJURNxEo5ex8U7hEyTqzaByI39NiVDSncMixtZjBeTD7EN7wWohn//V4Q/GPjy1iDJBDuQLUBiHtHIpkBVGtKPDTXpgcUpT48cJeAR2rZPOxx6+8VFedjwWSLsLy99RpG8BViASH5rJlFTT+ToqQE0dlLuYxgC+2Gl67vPNYGwC85bVQzVVqijTWeu1oo0mDMZ9rBh/a++nFdZyXP5sqWP0I915rLfkh82d+9bo14=}
